version: 2.1

jobs:
  deploy-oci:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - run:
          name: Install OCI CLI
          command: |
            apt-get update && apt-get install -y python3-pip
            pip3 install oci-cli
      - run:
          name: Terraform Init
          command: terraform init
      - run:
          name: Terraform Apply
          command: terraform apply -auto-approve

workflows:
  version: 2
  scheduled-deploy:
    triggers:
      - schedule:
          cron: "*/10 * * * *"
          filters:
            branches:
              only: main
    jobs:
      - deploy-oci
