version: 2.1

jobs:
  deploy-oci:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - run:
          name: Install OCI CLI
          command: |
            apt-get update && apt-get install -y python3-pip
            pip3 install oci-cli
      - run:
          name: Deploy to all zones
          command: |
            zones=("NTeU:EU-FRANKFURT-1-AD-1" "NTeU:EU-FRANKFURT-1-AD-2" "NTeU:EU-FRANKFURT-1-AD-3")
            for zone in "${zones[@]}"; do
              terraform init
              terraform apply -auto-approve -var="availability_domain=$zone" || continue
            done

workflows:
  version: 2
  scheduled-deploy:
    triggers:
      - schedule:
          cron: "*/10 * * * *"
          filters:
            branches:
              only: main
    jobs:
      - deploy-oci
